id: P009481
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14718
  title: 'ལྷོ་ཁ་མཚོ་སྨད་རྫོང་བོད་ལུགས་སྨན་པའི་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    c295ac4a4e2148688e57d3f305e780e0:
      image_group_id: I2PD18450
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
