id: P009481
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:40:44.598388
source_metadata:
  id: bdr:W1KG14718
  title: 'ལྷོ་ཁ་མཚོ་སྨད་རྫོང་བོད་ལུགས་སྨན་པའི་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས། '
  author: ''
  volumes:
    c295ac4a4e2148688e57d3f305e780e0:
      image_group_id: I2PD18450
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
